import os
import requests
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("AUTODB_API_KEY")
CONN_ID = os.getenv("AUTODB_CONNECTION_ID")
BASE_URL = "http://api.autodb.app/api/v1"

HEADERS = {"X-API-Key": API_KEY, "Content-Type": "application/json"}

def execute_agent_query(intent_prompt: str) -> str:
    """
    Takes a plain English prompt generated by the Brain and mutates/queries 
    the database via AutoDB, returning the resulting text string.
    """
    payload = {
        "prompt": intent_prompt,
        "execute": True,
        "caller": "agent",
        "guardrail": "permissive"
    }
    
    try:
        response = requests.post(
            f"{BASE_URL}/connections/{CONN_ID}/queries/generate", 
            headers=HEADERS, 
            json=payload,
            timeout=15
        )
        data = response.json()
        if data.get("success"):
            return str(data.get("data", {}).get("result", "Action completed within database."))
        else:
            return f"AutoDB Error: {data.get('error', {}).get('message', 'Unknown Error')}"
    except Exception as e:
        return f"Database integration error: {str(e)}"
